### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by spth** [stefaandesmet2003/stlinkswim#1]
I suggest to provide build instructions for those not familiar with platformio.

**Comment by stefaandesmet2003** [comment]
Hi, thanks for your interest.
Install platformio vs code extension, choose 'open project', and point to the root directory of this repo. 
Platformio will find the platformio.ini file, pull in the necessary packages (ststm32 & libopencm3)

![Schermafbeelding 2021-11-17 123359](https://user-images.githubusercontent.com/11933661/142193516-e8c8ae9e-d82e-4b47-b420-4066c1f8584f.jpg)

![Schermafbeelding 2021-11-17 123606](https://user-images.githubusercontent.com/11933661/142193526-e19c4a1d-2d81-43b3-a44f-323698be21d1.jpg)

click 'build'
click 'flash'
![Schermafbeelding 2021-11-17 123757](https://user-images.githubusercontent.com/11933661/142193810-fd7689df-9ec9-4228-802d-3b9204a5b150.jpg)

Does that work for you?
